---
- hosts: localhost #localhost means we are running on the same machine
  connection: local #playbook has to be executed on the same machine.
  vars:
    auth_source: msi
    #if using azure service principal instead of managed identity, add below after editing each tasks:
  #vars:
    #auth_source: env
  #vars_files:
    #- group_vars/all/pass.yml
  roles:
   - vm

